version: '3'

services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_DB: 'sifos'
      POSTGRES_USER: 'sifos'
      POSTGRES_PASSWORD: 'A12345678'
    ports:
      - "5422:5432"
  web:
    env_file:
        - .env.example
    restart: on-failure
    build: .
    command: gunicorn SIFO.wsgi -b :8000
    volumes:
      - .:/code
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - "81:81"
    volumes:
      - ./nginx/sifos.conf:/etc/nginx/conf.d/sifos.conf
    depends_on:
      - web
