# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-10 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20181104_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='estado',
            field=models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo')], default='Activo', max_length=50),
        ),
    ]
