# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-04 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Donador')),
            ],
            options={
                'db_table': 'financiacion_donacion',
            },
        ),
    ]
