# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-04 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0003_auto_20181104_1637'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poligono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('coordenadas_puntos', models.CharField(blank=True, max_length=200, null=True)),
                ('area', models.FloatField(blank=True, max_length=100, null=True)),
                ('perimetro', models.FloatField(blank=True, max_length=100, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Municipio')),
                ('tipo_patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.TipoPatron')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'terreno_poligono',
            },
        ),
        migrations.CreateModel(
            name='PuntoSiembra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('latitud', models.FloatField(blank=True, max_length=200, null=True)),
                ('longitud', models.FloatField(blank=True, max_length=200, null=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Especie')),
                ('poligono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terreno.Poligono')),
            ],
            options={
                'db_table': 'terreno_punto_siembra',
            },
        ),
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.CharField(blank=True, max_length=5, null=True)),
                ('humedad', models.CharField(blank=True, max_length=5, null=True)),
                ('altitud', models.FloatField(blank=True, max_length=200, null=True)),
                ('ph', models.CharField(blank=True, max_length=5, null=True)),
                ('url_video', models.CharField(blank=True, max_length=200, null=True)),
                ('donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Donador')),
                ('punto_siembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terreno.PuntoSiembra')),
            ],
            options={
                'db_table': 'terreno_siembra',
            },
        ),
    ]
