# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-04 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terreno', '0003_auto_20181104_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siembra',
            name='id',
        ),
        migrations.AlterField(
            model_name='siembra',
            name='punto_siembra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='terreno.PuntoSiembra'),
        ),
    ]
