# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-04 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=200, null=True)),
                ('porcentaje_oxigeno', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_carbono', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'general_especie',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('coordenadas', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'general_municipio',
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('gps', models.CharField(blank=True, max_length=200, null=True)),
                ('modelo', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Inactivo', 'Inactivo'), ('Activo', 'Activo')], default='Activo', max_length=50)),
            ],
            options={
                'db_table': 'general_robot',
            },
        ),
        migrations.CreateModel(
            name='TipoPatron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('figura', models.CharField(blank=True, max_length=200, null=True)),
                ('distancia_interna', models.IntegerField(default=1, null=True)),
            ],
            options={
                'db_table': 'general_tipo_patron',
            },
        ),
    ]
