# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-04 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_especiemunicipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50),
        ),
    ]
