# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-04 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20181104_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='coordenadas',
            new_name='latitud',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='codigo',
        ),
        migrations.AddField(
            model_name='municipio',
            name='longitd',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
