# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-10 15:21
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='valor',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=30),
        ),
    ]
